name: Project Issue Status Automations
on:
    issues:
        types:
            - labeled
jobs:
    check-for-in-progress-label:
        name: check_for_in_progress_label
        if: >
            github.event.label.name == 'status: in progress'
        runs-on: ubuntu-latest
        steps:
            - name: Move issue to In Progress
              uses: leonsteinhaeuser/project-beta-automations@v2.1.0
              with:
                  gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  user: aeviterna
                  project_id: 2
                  resource_node_id: ${{ github.event.issue.node_id }}
                  status_value: In progress
    check-for-done-label:
        name: check_for_done_label
        if: >
            github.event.label.name == 'status: done'
        runs-on: ubuntu-latest
        steps:
            - name: Move issue to Done
              uses: leonsteinhaeuser/project-beta-automations@v2.1.0
              with:
                  gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  user: aeviterna
                  project_id: 2
                  resource_node_id: ${{ github.event.issue.node_id }}
                  status_value: Done
